
//
// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2023, NVIDIA CORPORATION. All rights reserved.
// Author: John Linford <jlinford@nvidia.com>
//
// This file was autogenerated by kgen.py
//


const char * description = "4( 16(SCALAR_FMUL_32b) )";
unsigned long block_inst = 16;
unsigned long block_ops = (16*(1*1));
unsigned long unroll = 4;

void kernel(unsigned long iters)
{
    for (unsigned long i=0; i<iters; ++i) {
        asm volatile (
        "fmul s0, s8, s16 \n\t"
        "fmul s1, s9, s17 \n\t"
        "fmul s2, s10, s18 \n\t"
        "fmul s3, s11, s19 \n\t"
        "fmul s4, s12, s20 \n\t"
        "fmul s5, s13, s21 \n\t"
        "fmul s6, s14, s22 \n\t"
        "fmul s7, s15, s23 \n\t"
        "fmul s8, s16, s24 \n\t"
        "fmul s9, s17, s25 \n\t"
        "fmul s10, s18, s26 \n\t"
        "fmul s11, s19, s27 \n\t"
        "fmul s12, s20, s28 \n\t"
        "fmul s13, s21, s29 \n\t"
        "fmul s14, s22, s30 \n\t"
        "fmul s15, s23, s31 \n\t"
        "fmul s0, s8, s16 \n\t"
        "fmul s1, s9, s17 \n\t"
        "fmul s2, s10, s18 \n\t"
        "fmul s3, s11, s19 \n\t"
        "fmul s4, s12, s20 \n\t"
        "fmul s5, s13, s21 \n\t"
        "fmul s6, s14, s22 \n\t"
        "fmul s7, s15, s23 \n\t"
        "fmul s8, s16, s24 \n\t"
        "fmul s9, s17, s25 \n\t"
        "fmul s10, s18, s26 \n\t"
        "fmul s11, s19, s27 \n\t"
        "fmul s12, s20, s28 \n\t"
        "fmul s13, s21, s29 \n\t"
        "fmul s14, s22, s30 \n\t"
        "fmul s15, s23, s31 \n\t"
        "fmul s0, s8, s16 \n\t"
        "fmul s1, s9, s17 \n\t"
        "fmul s2, s10, s18 \n\t"
        "fmul s3, s11, s19 \n\t"
        "fmul s4, s12, s20 \n\t"
        "fmul s5, s13, s21 \n\t"
        "fmul s6, s14, s22 \n\t"
        "fmul s7, s15, s23 \n\t"
        "fmul s8, s16, s24 \n\t"
        "fmul s9, s17, s25 \n\t"
        "fmul s10, s18, s26 \n\t"
        "fmul s11, s19, s27 \n\t"
        "fmul s12, s20, s28 \n\t"
        "fmul s13, s21, s29 \n\t"
        "fmul s14, s22, s30 \n\t"
        "fmul s15, s23, s31 \n\t"
        "fmul s0, s8, s16 \n\t"
        "fmul s1, s9, s17 \n\t"
        "fmul s2, s10, s18 \n\t"
        "fmul s3, s11, s19 \n\t"
        "fmul s4, s12, s20 \n\t"
        "fmul s5, s13, s21 \n\t"
        "fmul s6, s14, s22 \n\t"
        "fmul s7, s15, s23 \n\t"
        "fmul s8, s16, s24 \n\t"
        "fmul s9, s17, s25 \n\t"
        "fmul s10, s18, s26 \n\t"
        "fmul s11, s19, s27 \n\t"
        "fmul s12, s20, s28 \n\t"
        "fmul s13, s21, s29 \n\t"
        "fmul s14, s22, s30 \n\t"
        "fmul s15, s23, s31 \n\t"
        : /* no input */
        : /* no output */
        : "s0", "s1", "s10", "s11", "s12", "s13", "s14", "s15", "s16", "s17", "s18", "s19", "s2", "s20", "s21", "s22", "s23", "s24", "s25", "s26", "s27", "s28", "s29", "s3", "s30", "s31", "s4", "s5", "s6", "s7", "s8", "s9"
        );
    }
}

