
//
// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2023, NVIDIA CORPORATION. All rights reserved.
// Author: John Linford <jlinford@nvidia.com>
//
// This file was autogenerated by kgen.py
//
#include <arm_sve.h>

const char * description = "4( 16(SVE_SMMLA_32b) )";
unsigned long block_inst = 16;
unsigned long block_ops = (16*(16*(8*svcntb()/32)));
unsigned long unroll = 4;

void kernel(unsigned long iters)
{
    for (unsigned long i=0; i<iters; ++i) {
        asm volatile (
        "smmla z0.s, z8.b, z16.b \n\t"
        "smmla z1.s, z9.b, z17.b \n\t"
        "smmla z2.s, z10.b, z18.b \n\t"
        "smmla z3.s, z11.b, z19.b \n\t"
        "smmla z4.s, z12.b, z20.b \n\t"
        "smmla z5.s, z13.b, z21.b \n\t"
        "smmla z6.s, z14.b, z22.b \n\t"
        "smmla z7.s, z15.b, z23.b \n\t"
        "smmla z8.s, z16.b, z24.b \n\t"
        "smmla z9.s, z17.b, z25.b \n\t"
        "smmla z10.s, z18.b, z26.b \n\t"
        "smmla z11.s, z19.b, z27.b \n\t"
        "smmla z12.s, z20.b, z28.b \n\t"
        "smmla z13.s, z21.b, z29.b \n\t"
        "smmla z14.s, z22.b, z30.b \n\t"
        "smmla z15.s, z23.b, z31.b \n\t"
        "smmla z0.s, z8.b, z16.b \n\t"
        "smmla z1.s, z9.b, z17.b \n\t"
        "smmla z2.s, z10.b, z18.b \n\t"
        "smmla z3.s, z11.b, z19.b \n\t"
        "smmla z4.s, z12.b, z20.b \n\t"
        "smmla z5.s, z13.b, z21.b \n\t"
        "smmla z6.s, z14.b, z22.b \n\t"
        "smmla z7.s, z15.b, z23.b \n\t"
        "smmla z8.s, z16.b, z24.b \n\t"
        "smmla z9.s, z17.b, z25.b \n\t"
        "smmla z10.s, z18.b, z26.b \n\t"
        "smmla z11.s, z19.b, z27.b \n\t"
        "smmla z12.s, z20.b, z28.b \n\t"
        "smmla z13.s, z21.b, z29.b \n\t"
        "smmla z14.s, z22.b, z30.b \n\t"
        "smmla z15.s, z23.b, z31.b \n\t"
        "smmla z0.s, z8.b, z16.b \n\t"
        "smmla z1.s, z9.b, z17.b \n\t"
        "smmla z2.s, z10.b, z18.b \n\t"
        "smmla z3.s, z11.b, z19.b \n\t"
        "smmla z4.s, z12.b, z20.b \n\t"
        "smmla z5.s, z13.b, z21.b \n\t"
        "smmla z6.s, z14.b, z22.b \n\t"
        "smmla z7.s, z15.b, z23.b \n\t"
        "smmla z8.s, z16.b, z24.b \n\t"
        "smmla z9.s, z17.b, z25.b \n\t"
        "smmla z10.s, z18.b, z26.b \n\t"
        "smmla z11.s, z19.b, z27.b \n\t"
        "smmla z12.s, z20.b, z28.b \n\t"
        "smmla z13.s, z21.b, z29.b \n\t"
        "smmla z14.s, z22.b, z30.b \n\t"
        "smmla z15.s, z23.b, z31.b \n\t"
        "smmla z0.s, z8.b, z16.b \n\t"
        "smmla z1.s, z9.b, z17.b \n\t"
        "smmla z2.s, z10.b, z18.b \n\t"
        "smmla z3.s, z11.b, z19.b \n\t"
        "smmla z4.s, z12.b, z20.b \n\t"
        "smmla z5.s, z13.b, z21.b \n\t"
        "smmla z6.s, z14.b, z22.b \n\t"
        "smmla z7.s, z15.b, z23.b \n\t"
        "smmla z8.s, z16.b, z24.b \n\t"
        "smmla z9.s, z17.b, z25.b \n\t"
        "smmla z10.s, z18.b, z26.b \n\t"
        "smmla z11.s, z19.b, z27.b \n\t"
        "smmla z12.s, z20.b, z28.b \n\t"
        "smmla z13.s, z21.b, z29.b \n\t"
        "smmla z14.s, z22.b, z30.b \n\t"
        "smmla z15.s, z23.b, z31.b \n\t"
        : /* no input */
        : /* no output */
        : "z0", "z1", "z10", "z11", "z12", "z13", "z14", "z15", "z16", "z17", "z18", "z19", "z2", "z20", "z21", "z22", "z23", "z24", "z25", "z26", "z27", "z28", "z29", "z3", "z30", "z31", "z4", "z5", "z6", "z7", "z8", "z9"
        );
    }
}

